language: cpp
os: osx
osx_image: xcode10
compiler: clang

notifications:
  email: false
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/504869183658655744/scZfH6ima89pQX_ezRSsO_7bSDJ_KMmhnOKrLk86vr6gNPtul_L9mZuoOGby6Sndh458
      on_sucess: always
      on_failure: always

install:
  - cmake .

script:
  - make